### ISSUE TITLE
请问老哥儿可不可以整一个 `react` 的

### ISSUE THREAD

**Issue by d1y** [zeit-ui/vue#111]
特别漂亮, 请问老哥可不可以整一个 `react` 版本的, 非常感谢Thanks♪(･ω･)ﾉ

**Comment by ofekashery** [comment]
Joining the request.
I've seen you have a React library ([zeit.co/design](https://zeit.co/design)), but it's not open source 😕

**Comment by unix** [comment]
暂时没有这个计划。
官方有一个 `design` 的页面，但并不是开源的，或者可以试试在 twitter 上问问。

**Comment by unix** [comment]
@d1y 

[ZEIT-UI React](https://github.com/zeit-ui/react) 已经开始 alpha 了，正在建设中，大家可以试用、提建议或是参与贡献。

@ofekashery 

Hey, a good news is that `ZEIT-UI React` is starting alpha testing, anyone can make suggestions or become a contributor.

🎉🎉
