### ISSUE TITLE
Can support date picker component? 

### ISSUE THREAD

**Issue by JesseEisen** [zeit-ui/vue#120]
# Feature request 🚀
datapicker component add 

I know that ZEIT does not support this component, so can you add it, or any suggestions about that?
Thanks

**Comment by unix** [comment]
`zeit-ui` will follow [zeit-design](https://zeit.co/design) as much as possible, so this feature needs to wait for a while. If you have an idea with `date picker`, you can contact *zeit-design team* by [feedback](https://zeit.co/feedback/general) or twitter, or try slack of zeit (i'm not sure)?

(i guess the design will not be update in a short time 😞)

**Comment by JesseEisen** [comment]
all right, Let's wait for that :smile:

**Comment by robertsamarji** [comment]
Would be great to see a date picker in Geist. Vercel now have a date picker (found in the "Usage" section of their project dashboard).

Fantastic work with Geist btw!
