### ISSUE TITLE
popup 组件与 header

### ISSUE THREAD

**Issue by mikumikulch** [zeit-ui/vue#140]
前端素人一枚，没框架就不会编程的那种。

想做点简单的页面，现在需要 header 还有 footer 以及 popup。请问咋办呀。

**Comment by unix** [comment]
参考 [#120](https://github.com/zeit-ui/vue/issues/120) 。对于没有设计稿的组件暂时不会添加。

你可以学习一下使用 `zi-col` `zi-row` 进行简单的布局。

**Comment by mikumikulch** [comment]
已成功实现 Header 。但是不知道 popup 应该怎么做，有大佬帮帮忙吗。

**Comment by unix** [comment]
可以参考一下 [Popover 组件的文档](https://vue.zeit-ui.co/zh-cn/popover)，里面有详细的用法。
