### ISSUE TITLE
header、footer

### ISSUE THREAD

**Issue by mikumikulch** [zeit-ui/vue#141]

**Comment by mikumikulch** [comment]
前端素人一枚，没框架就不会编程的那种。

想做点简单的页面，现在需要 header 还有 footer，已经 popup。请问咋办呀。

**Comment by unix** [comment]
参考 [#120](https://github.com/zeit-ui/vue/issues/120) 。对于没有设计稿的组件暂时不会添加。

你可以学习一下使用 `zi-col` `zi-row` 进行简单的布局。
