### ISSUE TITLE
dialog默认值为true时不显示

### ISSUE THREAD

**Issue by Larawei** [zeit-ui/vue#145]
# Bug report 🐞
dialog默认值为 `true` 是不显示
## Version & Environment
^2.3.2
## Expection
需要初始化时设置为 `false` 后，修改为  `true` 才显示

**Comment by unix** [comment]
这个问题在 [#146](https://github.com/zeit-ui/vue/pull/146) 合并后会被修复，CI 完成后会自动发布新的 Patch 版本 `2.3.3`，注意更新。
