### ISSUE TITLE
Add `Display` component

### ISSUE THREAD

**Issue by unix** [zeit-ui/vue#155]
# Feature request 🚀

`Display` component is added to improve the readability of normal layout.

### Expected:
  - Remove props `caption` & `shadow` on `zi-image`
  - Add component `Display`
  - Add props `darkBash` to `zi-code`

### Examples:
Refer to [React Component](https://react.zeit-ui.co/docs/components/display)

**Comment by yuler** [comment]
Hi, could you make the [zeit-ui/react](https://github.com/zeit-ui/react) repo open source?

I want contribution it

**Comment by unix** [comment]
Hey, the `zeit-ui/react` is still under development, and the project architecture may need to be **refactored**, which is not friendly to contributors. I am in the process of perf testing and will be online in the near future. (1 - 2 weeks 🤗🤗)

**Comment by yuler** [comment]
Oh I see. Waiting for your release.
