### ISSUE TITLE
Add Playground component/page

### ISSUE THREAD

**Issue by yuler** [zeit-ui/vue#160]
# Feature request 🚀

Playground component/page is play the component online

### Expected:
  - No breaking changes

### Examples:

Refer to [Zeit Playground](https://zeit.co/design/playground)

**Comment by unix** [comment]
Uh huh..
This component needs to implement **paste** and **component render**, It looks heavy. I suggest ignore it for now,  whats your opinion 🤔

**Comment by yuler** [comment]
Yes. I find [vuep](https://github.com/QingWei-Li/vuep) is good implement.

I think can find ideas from it.

**Comment by unix** [comment]
Well, do you want take it?

**Comment by yuler** [comment]
Yeah, I will try implement it.

witt <notifications@github.com> 于2020年3月12日周四 下午5:09写道：

**Comment by unix** [comment]
🎉
OK, You can create PR at any time, and don't forget to keep the `Playground` as simple and small as possible.

**Comment by yuler** [comment]
#162
