### ISSUE TITLE
Missing Card shadow style

### ISSUE THREAD

**Issue by WingLim** [zeit-ui/vue#170]
# About `styles` 🛠️
https://vue.zeit-ui.co/zh-cn/card
I can only found `zi-card` and `.zi-card.hoverable` style in @zeit-ui/vue/dist/zeit-ui.css and @zeit-ui/vue/lib/card.css.
Maybe you guys forgot to add shadow style?

**Comment by unix** [comment]
This is version 2.4. Sorry, it hasn't been released.
There are a few components that need to be improved. We will release the version in the next few days.
