### ISSUE TITLE
更改图标大小和颜色

### ISSUE THREAD

**Issue by pape2016** [zeit-ui/vue#177]
# About `styles` 🛠️

请问可以增加设置图标大小和颜色的属性吗？现在显示在页面上跟旁边的字体和元素大小不匹配，显得太大了，又没有办法缩小。还有颜色想改成红色的，默认是黑色的。可以在外面包一层div来设置颜色，但是加了一层div之后有时候会引起布局的变化，如果有一个属性可以直接设置颜色会更合理一些。

谢谢。

**Comment by unix** [comment]
图标本身就是一个 `SVG` 元素，就使用 CSS 控制 SVG 元素即可，包括颜色和大小。
