### ISSUE TITLE
Responsive Layout

### ISSUE THREAD

**Issue by msurguy** [zeit-ui/vue#178]
# About `styles` 🛠️

Hi! This is a great starter kit for many projects! 

I was wondering how you would achieve responsive column / row layout like Bootstrap provides, for example if I want layout split in 3 columns on desktop to become 1 column layout on mobile. 

What would you recommend to achieve responsive composition?

**Comment by unix** [comment]
The `Grid` component is what `zeit-ui/vue` lacks now, I'll make up for this ASAP.

**Comment by msurguy** [comment]
Thank you @unix! I really appreciate this project and you trying to help!
