### ISSUE TITLE
User and AutoComplete components

### ISSUE THREAD

**Issue by msurguy** [zeit-ui/vue#179]
# Feature request 🚀

Hi! I'd like to know if you were planning to port your User and AutoComplete components from React UI to this one. I'd even pay a small amount to get those in :) 

Thanks!

**Comment by unix** [comment]
Thank you for reminding me, this feature is already in Roadmap, and I'll solve it ASAP.

**Comment by Lzumikonata** [comment]
@unix The `Portals` will be implemented in Vue 3. In my opinion, we should defer implementation of `AutoComplete` component until Vue 3 is released.

**Comment by unix** [comment]
@Lzumikonata 
Yes, I saw it. Vue 3 will have a new feature called `Teleport`. I agree with you, there is no need to create this funciton manually at present.

We will consider the work related to `dropdown` component (`AutoComplete`) after Vue3. And the `User` component is implemented #181 .
