### ISSUE TITLE
Replace Popper v1 with Popper v2

### ISSUE THREAD

**Issue by msurguy** [zeit-ui/vue#189]
Popper.js V1 is a huge library and this project could be trimmed down significantly by replacing Popper V1 with V2. 

Here are bundle sizes before and after replacement:
Before:
<img width="392" alt="Screen Shot 2020-06-15 at 8 49 05 PM" src="https://user-images.githubusercontent.com/585833/84731813-f15dfd00-af4e-11ea-802a-96463abba9ff.png">

After:
<img width="549" alt="Screen Shot 2020-06-15 at 9 25 37 PM" src="https://user-images.githubusercontent.com/585833/84731811-ef943980-af4e-11ea-8f53-0c879f47c70e.png">

Here's the process I had to follow: 

1) Remove popperjs v1 and replace with 
` "@popperjs/core": "^2.4.2"`

2) In tooltip.vue:
```js
import { createPopper } from '@popperjs/core';
...
 mounted() {
    createPopper(this.$refs.host, this.$refs.inner, {
      placement: this.placement,
      modifiers: [
        {
          name: 'arrow',
          options: {
            element: this.$refs.arrow
          }
        },
        {
          name: 'offset',
          options: {
            offset: [0, 8]
          }
        }
      ]
    })
  },
```

Then, in tooltip.styl, remove all existing arrow styles and replace with:
```
.zi-tooltip-arrow,
.zi-tooltip-arrow::before {
  position: absolute;
  width: 8px;
  height: 8px;
  z-index: -1;
}

.zi-tooltip-arrow::before {
  content: '';
  transform: rotate(45deg);
  background: var(--geist-foreground);
}

.zi-tooltip-box[data-popper-placement^=bottom] .zi-tooltip-arrow
  top -4px

.zi-tooltip-box[data-popper-placement^=top] .zi-tooltip-arrow
  bottom -4px

.zi-tooltip-box[data-popper-placement^=left] .zi-tooltip-arrow
  right 0

.zi-tooltip-box[data-popper-placement^=right] .zi-tooltip-arrow
  left -8px
```

After that, the size is significantly trimmed!
Hope this helps!

**Comment by unix** [comment]
Thankyou for your proposal, this is a big improvement.
