### ISSUE TITLE
Modal Dialog - body jumps when open

### ISSUE THREAD

**Issue by msurguy** [zeit-ui/vue#198]
# Feature request 🚀

### Expected:

When dialog element is open, I would expect the page to stay in the same place. Currently the page jumps to the side because scrollbar is removed due to `overflow:hidden` set on the body. 

I'd recommend measuring the width of the scrollbar and maintaining padding on the body element to be equal to scrollbar width if it's present. 

I like how Bootstrap deals with this problem and here's the code they use: 
https://github.com/twbs/bootstrap/blob/main/js/src/modal.js#L459

**Comment by unix** [comment]
Good point, we will improve this detail.
