### ISSUE TITLE
checkbox 对钩可以居中吗

### ISSUE THREAD

**Issue by zhao9052** [zeit-ui/vue#44]
[prompt]:<>(please add labels first)  
Type:  
- [ ] Bug  
- [ ] Feature  
- [ ] Help   

Version & Environment:  

Description:  

Screenshots:  
![image](https://user-images.githubusercontent.com/48588118/54731929-f1484380-4bcb-11e9-9025-e0866f495c38.png)

**Comment by l1shen** [comment]
这个是 zeit ui 的风格
