### ISSUE TITLE
Can not install the package

### ISSUE THREAD

**Issue by NOVA-ME** [zeit-ui/vue#63]
Type:  
- [x] Help   

Version & Environment:  
latest version

Description:  
can not install the package

Screenshots:  
![image](https://user-images.githubusercontent.com/18442141/59276504-01cefe00-8c91-11e9-8263-56195f31c19c.png)

**Comment by WittBulter** [comment]
I can't reproduce this issue, but i guess there are following reasons:
  1. NPM mirror site not sync. (if you using mirror site, check by `npm config get userconfig`)
  2. node_modules cache. clear: `rm -rf node_modules package-lock.json`

also, check your `npm --version`, please keep me informed of any progress or problems.

**Comment by NOVA-ME** [comment]
> I can't reproduce this issue, but i guess there are following reasons:
> 
> 1. NPM mirror site not sync. (if you using mirror site, check by `npm config get userconfig`)
> 2. node_modules cache. clear: `rm -rf node_modules package-lock.json`
> 
> also, check your `npm --version`, please keep me informed of any progress or problems.

![image](https://user-images.githubusercontent.com/18442141/59317319-eac1f780-8cf4-11e9-8969-9c92ada8b3e4.png)
when I remove the npm_cache, everything is ok. Thank you so much 😄
