### ISSUE TITLE
部分组件没有注册依赖的组件

### ISSUE THREAD

**Issue by fengzilong** [zeit-ui/vue#75]
# Bug report 🐞

## Version & Environment

version: 1.1.3
system: macOS

比如

https://github.com/zeit-ui/vue/blob/master/packages/files/files.vue

其实依赖了 file-item，但是没有在 files 中使用 components 注册组件

导致直接引用 Files 组件时，会提示 zi-files-item 未注册

我是这样子使用的

```js
import Files from '@zeit-ui/vue/packages/files'

export default {
  components: { Files }
  template: `<Files :files="[]" />`
}
```

这里没有使用 Files.install，使用 Files.install 的话可以绕开这个问题，但是我觉得上面的使用方式也是比较常见的

## Expection

files 内部注册用到的组件

## Actual results (or Errors)

直接使用 files 会提示 zi-files-item 未注册

## 其他

其他组件可能也有类似问题

**Comment by WittBulter** [comment]
单个组件需要引入 Bundle。

重复 #74

**Comment by WittBulter** [comment]
PR #76 修复了单个组件的引入问题，但还是需要使用 `Component.install(Vue)` 引入，推荐在入口或单个文件内统一引入需要的单个组件。文档已经更新。

如果重复在单个组件上注册依赖组件 `components: {}` 会导致组件无法注册，因为现在针对每个组件单独 `bundle` 了一次 (导出 `component.js`)，如果引用单个组件只会引入单个包。提前打包是避免部分用户因为没有源代码的打包环境导致引入失败。

**Comment by WittBulter** [comment]
可以参照 [文档](https://zeit-vue.now.sh/docs/installation) 来引入单个组件，这样可以做到 `tree-shaking`。

另外如果你已经引入了非常多的单个组件，那么建议直接引入全部的组件。每个组件在单独打包时会携带一些公共函数和公共样式，在全部单个组件引入后可能造成公共函数与样式部分重复打包。(公共函数体积较低，可以忽略，公共样式可能 > 1k)

```js
import Vue from 'vue'
import '@zeit-ui/vue/lib/button.css'
import Button from '@zeit-ui/vue/lib/button.common'

Button.install(Vue)
```
